### ISSUE TITLE
[Feat] 피드 등록 세부 기능 추가 구현

### ISSUE THREAD

**Issue by inyoung0215** [FoodieLog/foodie-log-server#47]
## 🔨수정하는 이유
피드 등록 세부 기능 미구현

## 🧩 세부 내용
- [ ] 피드 등록 시 맛집 좋아요가 저장되지 않는 오류 수정
- [ ] 피드 등록 시 해당 맛집의 중복체크 기능 추가 구현

## 📖 참고 사항
중복 체크의 경우 맛집의 고유키를 무엇으로 설정할것인지 의논 필요.
`place_Id` vs `place_name, place_Address`

**Comment by chaewon12** [comment]
🫢🫢 이건 bug에 가까운 이슈네요
